apiVersion: v1
kind: Secret
metadata:
  name: "api-secrets"
type: Opaque
data:
  # set $apiSecret to a random value
  {{- $apiSecret := (randAlphaNum 32 | b64enc) }}
  # generate 32 chars long random string, base64 encode it and then double-quote the result string.
  django-api-secret: {{ $apiSecret | b64enc | quote }}
